name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # Only run on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          DB_USER: postgres
          DB_PASSWORD: liduhgs4678^@RCGLSAYDuyio
          DB_SERVER: db
          DB_NAME: spotnet
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start services
        run: |
          docker compose up -d --build --file docker-compose.dev.yaml

      - name: Wait for PostgreSQL
        run: |
          until docker compose exec db pg_isready -U postgres; do
            echo "Waiting for postgres..."
            sleep 5
          done

      - name: Run tests
        run: |
          docker-compose exec backend pytest tests

      - name: Tear down
        run: |
          docker compose down
